Colibri Compatibility - updated: swithced from /var/run to /run - added: create/remote mountpoints on demand - added: use device LABEL to create mountpoint - removed: need for locks

diff --git a/usbmount b/usbmount
--- a/usbmount
+++ b/usbmount
@@ -49,6 +49,8 @@ FILESYSTEMS=
 MOUNTOPTIONS=
 FS_MOUNTOPTIONS=
 VERBOSE=no
+USE_LOCK=no
+RUN_DIR=/run
 
 if [ -r /etc/usbmount/usbmount.conf ]; then
     . /etc/usbmount/usbmount.conf
@@ -65,11 +67,11 @@ if [ ! -x /sbin/blkid ]; then
     exit 1
 fi
 
-# Per Policy 9.3.2, directories under /var/run have to be created
+# Per Policy 9.3.2, directories under ${RUN_DIR} have to be created
 # after every reboot.
-if [ ! -e /var/run/usbmount ]; then
-    mkdir -p /var/run/usbmount
-    log debug "creating /var/run/usbmount directory"
+if [ ! -e ${RUN_DIR}/usbmount ]; then
+    mkdir -p ${RUN_DIR}/usbmount
+    log debug "creating ${RUN_DIR}/usbmount directory"
 fi
 
 umask 022
@@ -78,12 +80,15 @@ umask 022
 if [ "$1" = add ]; then
 
     # Acquire lock.
-    log debug "trying to acquire lock /var/run/usbmount/.mount.lock"
-    lockfile-create --retry 3 /var/run/usbmount/.mount || \
-	{ log err "cannot acquire lock /var/run/usbmount/.mount.lock"; exit 1; }
-    trap '( lockfile-remove /var/run/usbmount/.mount )' 0
-    log debug "acquired lock /var/run/usbmount/.mount.lock"
-
+    if [ x"$USE_LOCK" == x"yes" ]; then
+        log debug "trying to acquire lock /run/usbmount/.mount.lock"
+        lockfile-create --retry 3 /run/usbmount/.mount || \
+        { log err "cannot acquire lock /run/usbmount/.mount.lock"; exit 1; }
+        log err $(id)
+        trap '( lockfile-remove /run/usbmount/.mount )' 0
+        log debug "acquired lock /run/usbmount/.mount.lock"
+    fi
+    
     # Grab device information from device and "divide it"
     #   FIXME: improvement: implement mounting by label (notice that labels
     #   can contain spaces, which makes things a little bit less comfortable).
@@ -91,6 +96,9 @@ if [ "$1" = add ]; then
     FSTYPE=$(echo "$DEVINFO" | sed 's/.*[[:blank:]]TYPE="\([^"]*\)".*/\1/g; s/[[:blank:]]*//g;')
     UUID=$(echo "$DEVINFO"   | sed 's/.*[[:blank:]]UUID="\([^"]*\)".*/\1/g; s/[[:blank:]]*//g;')
     USAGE=$(echo "$DEVINFO"  | sed 's/.*[[:blank:]]USAGE="\([^"]*\)".*/\1/g; s/[[:blank:]]*//g;')
+    LABEL=$(echo "$DEVINFO"  | sed 's/.*[[:blank:]]LABEL="\([^"]*\)".*/\1/g; s/[[:blank:]]*//g;')
+    
+    LABEL_SAFE=$(echo $LABEL | sed 's/ /_/g')
 
     if ! echo $USAGE | egrep -q "(filesystem|disklabel)"; then
 	log info "$DEVNAME does not contain a filesystem or disklabel"
@@ -114,14 +122,17 @@ if [ "$1" = add ]; then
 	# types to mount.
 	if in_list "$fstype" "$FILESYSTEMS"; then
 	    # Search an available mountpoint.
-	    for v in $MOUNTPOINTS; do
-		if [ -d "$v" ] && ! grep -q "^[^ ][^ ]*  *$v " /proc/mounts; then
+	    #for v in $MOUNTPOINTS; do
+        v="${MEDIA_DIR}/${LABEL_SAFE}"
+		if ! grep -q "^[^ ][^ ]*  *$v " /proc/mounts; then
 		    mountpoint="$v"
 		    log debug "mountpoint $mountpoint is available for $DEVNAME"
 		    break
 		fi
-	    done
+	    #done
 	    if [ -n "$mountpoint" ]; then
+		mkdir -p "$v"
+		
 		# Determine mount options.
 		options=
 		for v in $FS_MOUNTOPTIONS; do
@@ -133,6 +144,8 @@ if [ "$1" = add ]; then
 		if [ -n "$MOUNTOPTIONS" ]; then
 		    options="$MOUNTOPTIONS${options:+,$options}"
 		fi
+		
+		mkdir -p "$mountpoint"
 
 		# Mount the filesystem.
 		log info "executing command: mount -t$fstype ${options:+-o$options} $DEVNAME $mountpoint"
@@ -187,8 +200,7 @@ elif [ "$1" = remove ]; then
 	if [ "$DEVNAME" = "$device" ]; then
 	    # If the mountpoint and filesystem type are maintained by
 	    # this script, unmount the filesystem.
-	    if in_list "$mountpoint" "$MOUNTPOINTS" &&
-		in_list "$fstype" "$FILESYSTEMS"; then
+	    if in_list "$fstype" "$FILESYSTEMS"; then
 		log info "executing command: umount -l $mountpoint"
 		umount -l "$mountpoint"
 
@@ -198,6 +210,8 @@ elif [ "$1" = remove ]; then
 		export UM_FILESYSTEM="$fstype"
 		log info "executing command: run-parts /etc/usbmount/umount.d"
 		run-parts /etc/usbmount/umount.d || :
+		
+		rm -rf "$mountpoint"
 	    fi
 	    break
 	fi
